TRAIN:
  seed: 42
  layers: 50
  base_lr: 0.01
  index_split: 5
  momentum: 0.9
  weight_decay: 0.0001
  epochs: 100
  aux_weight: 0.4
  print_freq: 50
  ignore_index: 0
  save_freq: 5
  save_path: './saved'
  evaluate: true
  batch_size: 16
  device: 'cuda:0'
TEST:
  seed: 42
  layers: 50
  base_lr: 0.01
  index_split: 5
  momentum: 0.9
  weight_decay: 0.0001
  epochs: 100
  aux_weight: 0.4
  print_freq: 50
  ignore_index: 0
  save_freq: 5
  save_path: './saved'
  evaluate: true
  batch_size: 16
